# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
- group: blocer_var

steps:
- script: echo $(variable1)

- task: DownloadGitHubRelease@0
  inputs:
    connection: 'github.com_blocer'
    userRepository: 'blocer/pipelines-java'
    defaultVersionType: 'latest'
    downloadPath: '$(System.ArtifactsDirectory)'
