# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

resources:
  repositories:
  - repository: blocer
    type: github
    endpoint: github.com_blocer
    name: blocer/nodejs
  - repository: blocer
    type: github
    endpoint: github.com_blocer
    name: blocer/pipelines-java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
- group: blocer_var

steps:
- script: echo $(variable1)

- script: ls $(System.ArtifactsDirectory)
